format_version: 3
pipelines:
  ci-build-and-test:
    group: demo
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    materials:
      git:
        git: https://github.com/charlottecampbell193/test-pipelines.git
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
    - defaultStage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        environment_variables:
          DOCKER_IMAGE_NAME: test-docker
          DOCKER_IMAGE_TAG: latest
        approval:
          type: success
        jobs:
          defaultJob:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -f Dockerfile.ci -t ${DOCKER_IMAGE_NAME} .
                command: /bin/bash
                run_if: passed
